#create database internship;
#create database hivemetastore;
#CREATE USER 'hive' IDENTIFIED BY 'admin';
#GRANT ALL PRIVILEGES ON hivemetastore.* TO 'hive'@'%';
#FLUSH PRIVILEGES;
#CREATE USER 'srilakshmi' IDENTIFIED BY 'sri@2000';
#GRANT ALL PRIVILEGES ON internship.* TO 'srilakshmi'@'%';
#FLUSH PRIVILEGES;
#CREATE TABLE pet (name VARCHAR(20), owner VARCHAR(20), species VARCHAR(20), sex CHAR(1), birth DATE, death DATE);
#INSERT INTO pet VALUES ('Puffball','Diane','hamster','f','1999-03-30',NULL);
#select * from pet;